### ISSUE TITLE
iOS SdkboxPlay, inc. achievement remain in state:2 (hidden)

### ISSUE THREAD

**Issue by whitegfx** [sdkbox/issues#1]
Incremental achievement still remain in state 2, even if unlocked by unlockAchievement function or automatically after incrementAchievement (current_steps:100.0). Function loadAchievements(true) return json which contain state:2 for achievement with current_steps:100.0.

## Enviroment ##
- iOS 9.3.5 (iPhone 4S), 10.2 (iPhone 6)
- cocos2d-x 3.14, sdkboxplay 2.3.9, OS Sierra 10.12.2, Xcode Version 8.2.1 (8C1002)

## Steps to reproduce ##
1. create "hidden" incremental achievement 
- itunes achievement id:flip_cards2, Reference Name:flip_cards2, hidden:yes, Achievable More Than Once:no
- liveops id: flip_cards2, name: flip_cards2n
2. publish cloud config, download config to project, 
3. call loadAchievements(true), to check correct values
4. call showAchievements to check achievement state before increment
5. call incrementAchievement several times until current_steps = 100.0
6. call loadAchievements(true)
7. call showAchievements to check achievement state before increment

## Checked to be sure ##
- [x] itunes/liveops/localconfig
- [x] itunes Game Center:on
- [x] itunes achievement id:flip_cards2, Reference Name:flip_cards2, hidden:yes, Achievable More Than Once:no
- [x] liveops id: flip_cards2, name: flip_cards2n
- [x] achievement is hidden in iOS UI, before increment or unlock, checked with showAchievements
- [x] achievement  can be incremented, increment is correctly reported
- [x] achievement  can be unlocked, event is fired (new:1)
- [x] achievement is unlocked iOS UI when current_steps = 100.0, checked with showAchievements

**Comment by whitegfx** [comment]
Hi, Is it solved in v2.3.11.3? thank you

**Comment by darkdukey** [comment]
Should be fixed in 2.3.11

**Comment by whitegfx** [comment]
Bad news, tested now with 2.3.11.3, simple test and still same. Something must be wrong.
 1. reset all achievements, restart game
 2. report some flips for the flip_cards_1, its open/not hidden from the start, state is ok.
 3. fetch achi json info
 4. report some flips to flip_cards_2
 5. fetch achi json info

See the state before and after please
BEFORE: Load fresh json achievements before next flips reporting
```
  {
    "achieved_description": "Flip 50 cards!",
    "current_steps": 100,
    "id": "flip_cards_1",
    "last_updated_timestamp": 1489179904,
    "name": "Rookie",
    "replayable": false,
    "state": 0,
    "total_steps": 100,
    "type": 1,
    "xp_value": 20
  },
  {
    "current_steps": 0,
    "id": "flip_cards_2",
    "last_updated_timestamp": 0,
    "name": "Rider",
    "replayable": false,
    "state": 2,
    "total_steps": 100,
    "type": 1,
    "unachieved_description": "Flip 500 cards!",
    "xp_value": 30
  },
```
AFTER: reporting to flip_cards_2, again load fresh json achievements and still in state 2 and total steps 100
```
  {
    "achieved_description": "Flip 50 cards!",
    "current_steps": 100,
    "id": "flip_cards_1",
    "last_updated_timestamp": 1489179904,
    "name": "Rookie",
    "replayable": false,
    "state": 0,
    "total_steps": 100,
    "type": 1,
    "xp_value": 20
  },
  {
    "current_steps": 3,
    "id": "flip_cards_2",
    "last_updated_timestamp": 1489180032,
    "name": "Rider",
    "replayable": false,
    "state": 2,
    "total_steps": 100,
    "type": 1,
    "unachieved_description": "Flip 500 cards!",
    "xp_value": 30
  },
```

**Comment by yinjimmy** [comment]
Please check `"current_steps": 3,` not ` "total_steps": 100,`.

**Comment by whitegfx** [comment]
If the initial state is hidden, any increment must switch the state to the revealed (1). flip_cards_2 was hidden in iOS gui and after little increment 3 is revealed in iOS gui, and his state still remain in 2 (hidden).' even if current_steps is 100 or 3. As you see I report and test bug for current_steps.  From posted json you see that current_steps = 3 and state is 2.

**Comment by yinjimmy** [comment]
https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/GameKit_Guide/Achievements/Achievements.html#//apple_ref/doc/uid/TP40008304-CH7-SW8

```
If the achievement was previously hidden, it is revealed to the player. The achievement
 is revealed even if your player has made no actual progress on the achievement 
(a percentage of 0.0).
```

**Comment by yinjimmy** [comment]
Fixed it.
