### ISSUE TITLE
IAPListener::onCanceled problem on iOS

### ISSUE THREAD

**Issue by haligalaph** [sdkbox/issues#10]
1) open app and try to buy something
2) close app by pressing "Home" before purchase dialog will appear
3) press "Cancel" when purchase dialog will appear
4) open multitasking screen and unload app from memory 
5) relaunch app

After registering IAPListener, onCanceled(const Product& p) will be called. But all fields of Product will be empty, so you will never know which one purchase was cancelled.

**Comment by yinjimmy** [comment]
good case.
