### ISSUE TITLE
crash in IabHelper.getPurchases

### ISSUE THREAD

**Issue by Dimon4eg** [sdkbox/issues#11]
Hi,

IAP crashes sometimes.

I see crash stack from Firebase error reporting:

Exception java.lang.NullPointerException:
com.sdkbox.plugin.util.iap.IabHelper.getPurchases (IabHelper.java:1130)
com.sdkbox.plugin.util.iap.IabHelper.getAllPurchases (IabHelper.java:1150)
com.sdkbox.plugin.SDKBoxIAPGooglePlay.getPurchases (SDKBoxIAPGooglePlay.java:272)
com.sdkbox.plugin.SDKBoxIAPGooglePlay.restorePurchase (SDKBoxIAPGooglePlay.java:256)
org.cocos2dx.lib.Cocos2dxRenderer.nativeRender (Cocos2dxRenderer.java)
org.cocos2dx.lib.Cocos2dxRenderer.onDrawFrame (Cocos2dxRenderer.java:104)
android.opengl.GLSurfaceView$GLThread.guardedRun (GLSurfaceView.java:1531)
android.opengl.GLSurfaceView$GLThread.run (GLSurfaceView.java:1248)

Another similar crash:
Exception java.lang.NullPointerException: Attempt to invoke interface method 'android.os.Bundle com.android.vending.billing.IInAppBillingService.getPurchases(int, java.lang.String, java.lang.String, java.lang.String)' on a null object reference
com.sdkbox.plugin.util.iap.IabHelper.getPurchases (IabHelper.java:1130)
com.sdkbox.plugin.util.iap.IabHelper.getAllPurchases (IabHelper.java:1150)
com.sdkbox.plugin.SDKBoxIAPGooglePlay.getPurchases (SDKBoxIAPGooglePlay.java:272)
com.sdkbox.plugin.SDKBoxIAPGooglePlay.restorePurchase (SDKBoxIAPGooglePlay.java:256)
org.cocos2dx.lib.Cocos2dxRenderer.nativeRender (Cocos2dxRenderer.java)
org.cocos2dx.lib.Cocos2dxRenderer.onDrawFrame (Cocos2dxRenderer.java:104)
android.opengl.GLSurfaceView$GLThread.guardedRun (GLSurfaceView.java:1535)
android.opengl.GLSurfaceView$GLThread.run (GLSurfaceView.java:1240)

Cocos2d-js 3.14
IAP 2.3.11.3

**Comment by yinjimmy** [comment]
Will firebase catch the error logcat ?
In internal, when and exception occurs, the plugin print the stack track like:

```
e.printStackTrace();
```

**Comment by Dimon4eg** [comment]
No, it happens in production.
I can't reproduce it by my self.
