### ISSUE TITLE
[iOS] AdMob plugin doesn't work properly

### ISSUE THREAD

**Issue by drakon-ag** [sdkbox/issues#12]
Steps to reproduce:
1. Ad two intersitial ads in `sdkbox_config.json`
Example:
```
    "ios": {
        "AdMob": {
            "test": false,
            "ads": {
                "reset_level": {
                    "type": "interstitial", 
                    "id": "ca-app-pub-0"
                },
                "next_level": {
                    "type": "interstitial",
                    "id": "ca-app-pub-1"
                },
                "home": {
                    "width": 300, 
                    "type": "banner", 
                    "id": "ca-app-pub-1329374026572143/3847466511", 
                    "alignment": "bottom", 
                    "height": 50
                }, 
                "rewarded": {
                    "type": "rewarded_video", 
                    "id": "ca-app-pub-1329374026572143/7991602916"
                }
            }
```
(put some vaild id in `next_level` and `reset_level`)

2. Set an AdMob listnerer with `sdkbox::PluginAdMob::setListener(listener);`
3. Call: `sdkbox::PluginAdMob::show("reset_level");`
4. Dismiss the ad
5. Observe `void adViewDidDismissScreen(const std::string &name)` is called with key equals to `next_level`.

The bug seems does not affect Android OS.

Configuration:
- XCode 8.3.2
- Device: iPad mini 2, iOS 10.3.1
- Cocos2d-x 3.13.1
- installed packages:
     v2.3.13.2 admob
     v2.3.13.2 flurryanalytics
     v2.3.13.2 googleplayservices

**Comment by yinjimmy** [comment]
Thanks for your report.

I test with sdkbox_config.json
```json
"ios": {
        "AdMob":{
            "test":false,
            "ads":{
                "home":{
                    "id":"ca-app-pub-1329374026572143/3847466511",
                    "type":"banner",
                    "alignment":"bottom",
                    "width":300,
                    "height":50
                },
                "reset_level":{
                    "id":"ca-app-pub-1329374026572143/4185543717",
                    "type":"interstitial"
                },
                "next_level":{
                    "id":"ca-app-pub-1329374026572143/9390403312",
                    "type":"interstitial"
                },
                "rewarded":{
                    "id":"ca-app-pub-1329374026572143/7991602916",
                    "type":"rewarded_video"
                }
            }
        }
    },
```

console log:
```shell
adViewDidReceiveAd:home
adViewDidReceiveAd:next_level
adViewDidFailToReceiveAdWithError:rewarded error message[No ad returned from any ad server.]
adViewWillPresentScreen:next_level
adViewDidDismissScreen:next_level
adViewWillDismissScreen:next_level
adViewDidReceiveAd:next_level
```

**Comment by yinjimmy** [comment]
@drakon-ag what's your steps?

**Comment by drakon-ag** [comment]
Hi yinjimmy, thanks for your support!
Using the same your `sdkbox_config.json`:

I call (in order):

```
sdkbox::PluginAdMob::init();
// setup the listener
sdkbox::PluginAdMob::show("reset_level"); // use "reset_level" key
```

and i get:

```
adViewWillPresentScreen: next_level
// dismiss the ad here
adViewDidDismissScreen: next_level
```
Note "next_level" key instead of "reset_level"

I did not see other AdMob listener calls, and I do not cache Ads before call "show".

**Comment by yinjimmy** [comment]
En, currently PluginAdmob design for one banner/interstitial/banner, if you have more than one, you can cache("reset_level"), and when "reset_level" ready, call show("reset_level").

I'll try to make multi Ad in next release. ;)

**Comment by drakon-ag** [comment]
@yinjimmy it seems to work properly if cache "reset_level" before calling `show`.
However I think the API behaviour should be adjusted:
if I do not cache "prev_level" neither "next_level", why calling show on "reset_level" trigger the "next_level" ad?

**Comment by yinjimmy** [comment]
cause admob try to load a random ad, but now supports multi banners.
