### ISSUE TITLE
[iOS] AdMob rewarded videos don't work

### ISSUE THREAD

**Issue by drakon-ag** [sdkbox/issues#13]
- devices test on: iPhone 7
- developing environments
   - Xcode version: 8.3.2

Steps to Reproduce:

1. Build [admob samples](https://github.com/sdkbox/sdkbox-sample-admob)
2. Tap on "load rewarded video"
3. Observe the following error message:
```
admob_cpp-mobile[4633:1176411] <Google> Cannot find an ad network adapter with the name(s): com.google.DummyAdapter. Remember to link all required ad network adapters and SDKs, and set -ObjC in the 'Other Linker Flags' setting of your build target.
admob_cpp-mobile[4633:1176290] adViewDidFailToReceiveAdWithError name=rewarded, msg=No ad returned from any ad server.
```

The same happens trying to integrate rewarded videos in my personal projects.

**Comment by drakon-ag** [comment]
It seems it was a backend problem, today everything works!

**Comment by drakon-ag** [comment]
The issue is back!
Both with [admob samples](https://github.com/sdkbox/sdkbox-sample-admob) and my personal project (using different ad key).
Anyone knows why this happens?

**Comment by yinjimmy** [comment]
AHA!

http://discuss.cocos2d-x.org/t/sdkbox-2-3-12-release-admob-reward-video/35867/51

> no reward callback on iOS simulator (works before) , but works on device

Could you please test it on device, I checked iPhone4s and iPhone 6s.

**Comment by drakon-ag** [comment]
Rewarded video works well with version v2.3.14.3 on iOS.
