### ISSUE TITLE
AdMob listener doesn't have a consistent behaviour on different platforms.

### ISSUE THREAD

**Issue by drakon-ag** [sdkbox/issues#14]
Steps to reproduce:
1) show a rewarded video
2) dismiss the video before it ends
3) Observe:
   - on iOS `adViewWillDismissScreen` is called but not `adViewDidDismissScreen`
   - on Android `adViewDidDismissScreen` is called but not `adViewWillDismissScreen`

1) show an interstitial ad
2) dismiss the ad
3) Observe:
   - on Android `adViewWillDismissScreen` doesn't get called

sdkbox packages:
```
installed packages:
     v2.3.13.2 admob
     v2.3.13.2 flurryanalytics
     v2.3.13.2 googleplayservices
```

**Comment by yinjimmy** [comment]
Thanks for your report,

**Comment by yinjimmy** [comment]
I have fixed this issue, and released in 2.3.14.

**Comment by drakon-ag** [comment]
Hi @yinjimmy 
I made a test with the version  v2.3.14.3 on iOS.
The listener works well with interstitial ads, but only `adViewWillDismissScreen` is called when a rewarded video is dismissed!

**Comment by yinjimmy** [comment]
Yes, but there no callback in AdMob SDK when a rewarded video will dismiss.
So no callback in SDKBox plugin.
