### ISSUE TITLE
iAP Android.mk is not correct

### ISSUE THREAD

**Issue by drakon-ag** [sdkbox/issues#15]
- cocos2d-x version: 3.15
- developing environments
   - iap version:  v2.3.13.5

Steps to Reproduce:
1.  Create an empty project `cocos new -l cpp Test`
2.  Go into the project folder `cd Test`
3.  Add iap plugin `sdkbox import iap`
4. Open the project `proj.android-studio`with Android Studio
5. The build fails because Android Studio doesn't find the library `android_native_app_glue`

**Comment by darkdukey** [comment]
This is caused by latest NDK, can you use ndk10e for now?

**Comment by drakon-ag** [comment]
Hi @darkdukey 
is this issue related with [this](http://discuss.cocos2d-x.org/t/sdkbox-admob-doesnt-load-ads-on-android/36825/6) ?

**Comment by yinjimmy** [comment]
1. remove android_native_app_glue
or
2. add `APP_ALLOW_MISSING_DEPS := true` into Android.mk

**Comment by drakon-ag** [comment]
@yinjimmy 
The project seems to work just removing `android_native_app_glue`.
Is `APP_ALLOW_MISSING_DEPS := true` useful?

**Comment by yinjimmy** [comment]
> Is APP_ALLOW_MISSING_DEPS := true useful?

sometimes ;)
