### ISSUE TITLE
[Android 4.3] AdMob plugin doesn't work properly

### ISSUE THREAD

**Issue by drakon-ag** [sdkbox/issues#17]
- tested on: Samsung Galaxy S3 (Android 4.3)
- developing environments
   - Android Studio v2.3.3

Steps to Reproduce:

1. Build [admob samples](https://github.com/sdkbox/sdkbox-sample-admob)
2. Show a rewarded video or an interstitial ad
3. Observe: the ads are not presented properly (you get a black screen or an error)

The plugin seems to work fine with Android version > 5.0.1

**Comment by yinjimmy** [comment]
I'll test on Android 4.1 tomorrow, thanks.

**Comment by yinjimmy** [comment]
Both rewarded video and interstitial ad works fine on Xiaomi Android 4.2.1.

**Comment by drakon-ag** [comment]
Hi @yinjimmy 
AdMob (both interstitial and rewarded videos) doesn't work on my Galaxy S3 (Android 4.3).
I'm not sure if this is a SDKBOX bug, because I have the same problem with apps downloaded from the store.
Maybe the bug is inside the Google AdMob library.
It could by a nice try to update the underlying libraries.
I can help you if you need a tester.

**Comment by yinjimmy** [comment]
In 2.3.15, we upgrade Google Play Services to 11.0.1. Let's test the library.

You can upgrade yourself with https://github.com/darkdukey/Google-Play-Service-Lite

**Comment by yinjimmy** [comment]
version 2.3.15 has been released, and the Google Play Services upgrade to 11.0.1. Could you test this sample again? with:
```
sdkbox update
```

I can not cache ads with `ERROR_CODE_NO_FILL`:
```
   cocos2d-x debug info  D  adViewDidFailToReceiveAdWithError name=home, msg=ERROR_CODE_NO_FILL
   cocos2d-x debug info  D  adViewDidFailToReceiveAdWithError name=gameover, msg=ERROR_CODE_NO_FILL
   cocos2d-x debug info  D  adViewDidFailToReceiveAdWithError name=rewarded, msg=ERROR_CODE_NO_FILL
```

will try after several hours.
