### ISSUE TITLE
SdkboxPlay achievements documentation corrections

### ISSUE THREAD

**Issue by whitegfx** [sdkbox/issues#2]
Hi here are some suggestions for the docs.

## where ##
http://docs.sdkbox.com/en/plugins/sdkboxplay/v3-cpp/

## what ##
- Android fields:
  - "xp_value" : string,   // experience value
    - on all platforms xp_value must be same, change to number
  - current_steps", missing start quote
- iOS fields:
  - "xp_value" : number, int
    - remove int
  - iOS only fields:, badly formated json code markdown
    - add unachieved_description field
- iOS Prerequisites add links for how-tos:
  - achievements: https://developer.apple.com/library/content/documentation/LanguagesUtilities/Conceptual/iTunesConnectGameCenter_Guide/Achievements/Achievements.html#//apple_ref/doc/uid/TP40013726-CH3-SW3
  - leaderboards
https://developer.apple.com/library/content/documentation/LanguagesUtilities/Conceptual/iTunesConnectGameCenter_Guide/Leaderboards/Leaderboards.html#//apple_ref/doc/uid/TP40013726-CH2-SW47
- add note for number type, json response value may contain integer or with precision (to avoid deserialization problems if anyone depend on the format). In android score fields is long why?
  - Any idea how to describe number type for responses to avoid future problems when they change the precision for example? Some agreement that they never chage ;-) Number types are known and fixed?(add them) Or they can change in the future (now some values comes as int, later can come as float/double?) - make a note

Thank you.

**Comment by darkdukey** [comment]
Thanks for your feedback, I've fixed most of the issue

I believe the score format long is a mistake, we'll add new method `submit_float` to address that.

**Comment by whitegfx** [comment]
Thank you for you edits, almost done.
- iOS achi field "description" is something new for next release? If not remove it from iOS fields.
- iOS state, add number type instead of 1, to be compatible with android types, you can add // always 1 = incremental, on iOS all achievemtns are incremental.
- iOS replayable field now comes as number, but type is boolean (something new for next release?)

thank you and have a nice day

**Comment by darkdukey** [comment]
The documentation should be updated, "replayable" will be corrected in next release.

**Comment by whitegfx** [comment]
Checked, ok. Many thanks for corrections.
