### ISSUE TITLE
[Android, OneSignal] Wrong notification JSON format

### ISSUE THREAD

**Issue by drakon-ag** [sdkbox/issues#20]
Steps to reproduce:

1) Setup a listener and implement the following:
```
void onNotificationOpened(const std::string &message) {
    log("%s, message: %s", __func__, message.c_str());
}
```
2) Send a notification from the One Signal dashboard, open it in an iOS device and observe the message:

`{"notification":{"payload":{"body":"Test","sound":"default","title":"Test","notificationID":"0c51426b-39bd-4d41-a760-8676b057482b","rawPayload":{"aps":{"alert":{"title":"Test","body":"Test"},"sound":"default"},"custom":{"a":{"actionSelected":"com.apple.UNNotificationDefaultActionIdentifier","my_key":"my_value","actionButtons":[]},"i":"0c51426b-39bd-4d41-a760-8676b057482b"}},"additionalData":{"actionSelected":"com.apple.UNNotificationDefaultActionIdentifier","my_key":"my_value","actionButtons":[]}},"shown":true,"displayType":2},"action":{"type":1,"actionID":"com.apple.UNNotificationDefaultActionIdentifier"}}`

The JSON syntax is **correct**

3) Do the same experiment on an Android device:

`{"action":{"type":0},"notification":{"isAppInFocus":false,"shown":true,"androidNotificationId":69733731,"displayType":0,"payload":{"notificationID":"0c51426b-39bd-4d41-a760-8676b057482b","title":"Test","body":"Test","additionalData":"{\"my_key\":\"my_value\"}","lockScreenVisibility":1,"groupMessage":"","fromProjectNumber":"683959924490","rawPayload":"{\"google.sent_time\":1499844603339,\"custom\":\"{\\\"a\\\":{\\\"my_key\\\":\\\"my_value\\\"},\\\"i\\\":\\\"0c51426b-39bd-4d41-a760-8676b057482b\\\"}\",\"pri\":\"5\",\"from\":\"683959924490\",\"alert\":\"Test\",\"title\":\"Test\",\"grp_msg\":\"\",\"google.message_id\":\"0:1499844603344266%8fc7b100f9fd7ecd\",\"notificationId\":69733731}"}}}
`

Observe redundant escaping characters:
`"additionalData":"{\"my_key\":\"my_value\"}"`
Observe the `rawPayload` is quite different on Android (it contains many `\ `characters).

The JSON parser fails to parse the `additionalData` object  on Android (useful when the developer wants to add custom payload to the notification).

**Comment by yinjimmy** [comment]
It seems a bug in `OneSignal SDK`  https://github.com/OneSignal/OneSignal-Android-SDK/blob/master/OneSignalSDK/onesignal/src/main/java/com/onesignal/OSNotificationOpenResult.java#L41

**Comment by drakon-ag** [comment]
@yinjimmy 
Is there a GitHub open issue? The bug is quite serious.

**Comment by yinjimmy** [comment]
Checked with OneSignal 3.5.x,
```
{
  "action": {
    "type": 0
  },
  "notification": {
    "isAppInFocus": false,
    "shown": true,
    "androidNotificationId": -1244730248,
    "displayType": 0,
    "payload": {
      "notificationID": "d548f778-7c54-41d8-865b-5b3ac357c2ac",
      "title": "test2",
      "body": "cc",
      "additionalData": {
        "sbkey": "sbvalue"
      },
      "lockScreenVisibility": 1,
      "groupMessage": "",
      "fromProjectNumber": "517386718969",
      "priority": 5,
      "rawPayload": "{\"google.sent_time\":1499931193925,\"custom\":\"{\\\"a\\\":{\\\"sbkey\\\":\\\"sbvalue\\\"},\\\"i\\\":\\\"d548f778-7c54-41d8-865b-5b3ac357c2ac\\\"}\",\"pri\":\"5\",\"from\":\"517386718969\",\"alert\":\"cc\",\"title\":\"test2\",\"grp_msg\":\"\",\"google.message_id\":\"0:1499931193986824%99ed6a75f9fd7ecd\",\"notificationId\":-1244730248}"
    }
  }
}
```


The `additionalData` is correct. 
https://github.com/OneSignal/OneSignal-Android-SDK/blob/master/OneSignalSDK.jar?raw=true

**Comment by drakon-ag** [comment]
@yinjimmy 
I checked too.
`additionalData` is correct with the new jar! 🎉

**Comment by yinjimmy** [comment]
I close this issue. 💯
