### ISSUE TITLE
IAP finish transaction functionality

### ISSUE THREAD

**Issue by haligalaph** [sdkbox/issues#21]
There is no analogue of finishTransaction method from StoreKit in iap plugin.
So if I need to send information about purchased inapp to my server and something goes wrong, inapp will be lost forever. Because finishTransaction method already has been called inside plugin.

**Comment by yinjimmy** [comment]
En, you can store the information in location, then send them to your server?

But why inapp will be lost when finish the transaction?

**Comment by haligalaph** [comment]
My app won't be notified about finished transaction any after. Yes, of course, I can store information about transactions by myself, but Apple has already implemented this functionality. So why should I rewrite it?

**Comment by darkdukey** [comment]
Yes, the main concern when we design the IAP api is to make it easy to use, that's why we hide a lot of steps from the average user.

If you want a really safe implementation, I would suggest that save all the user info on your server, and after IAP success, you'll get a receipt, once you verify the receipt, you can update user's coin/gem, item on the server, then sync the account from your server to client.

**Comment by haligalaph** [comment]
Yes, all user info is stored on server. Once I get notification about success IAP, I will send message to the server. So user's coins will be updated on server side. But if server doesn't receive this message for some reason, IAP will be lost. Transaction has been finished, and client won't get notification about it again. If I could manually call finishTransaction, I would call it only after getting responce from server, that user's balance has been updated.

**Comment by haligalaph** [comment]
Simplicity of using sdkbox is one of its big benefits. But for correct implementation of IAP in client-server schema, finishTransaction is definitely needed.

**Comment by darkdukey** [comment]
Yes, I agree with this, maybe we can add an option `setAutoFinishTransaction(false)` if that flag is set then developer will have to call `finishTransaction` themselves.

**Comment by haligalaph** [comment]
It would be great.

**Comment by yinjimmy** [comment]
http://discuss.cocos2d-x.org/t/sdkbox-2-3-17-1/39242

Thanks for using SDKBox.
