### ISSUE TITLE
AdMob Plugin on iPhone X does not take safe area into account.

### ISSUE THREAD

**Issue by 0megaD** [sdkbox/issues#26]
When drawing on the iPhone X you will have a safe area and an unsafe area to draw into, see the following image:

https://cdn-images-1.medium.com/max/1600/1*qlTFQRv0PJM4OVasU5Qu6A.png

When using SDKBOX AdMob plugin, a 'bottom' aligned Ad will show in the unsafe area of the iPhone X, making it show up underneath the Home bar. This makes it impossible to release for iPhone X as the store won't allow this kind of ad placement.

Please add a fix or option to allow us to position the Ad in the 'safe area' of the iPhone X.

**Comment by yinjimmy** [comment]
Thanks for your report. I'll make a fix and let u know.

**Comment by yinjimmy** [comment]
will release a 2.3.17.3 to fix this.

**Comment by 0megaD** [comment]
Awesome! Hope the release will be soon.  😄 (For Admob plugin specifically)

**Comment by 0megaD** [comment]
http://discuss.cocos2d-x.org/t/sdkbox-admob-for-iphone-x/39636/18?u=0mega

I tried using sdkbox import admob --staging.
It said it was using 2.3.17.3 but in the app the ads still went outside of the safe area. (See screenshot & thread)

![screen shot 2017-11-20 at 16 15 35](https://user-images.githubusercontent.com/2573161/33029278-75b074b8-ce18-11e7-9fc7-c1d7ff769dca.png)

**Comment by 0megaD** [comment]
It's working for banner ads, but interstitials are still showing the close button in the unsafe area.
There was an update to Google Ads SDK which fixes this issue.

> 7.26.0 | 2017‑11‑17 | iPhone X support.For full screen ads, the default close button now renders within the safe area.Removed the nativeAd property from GADAdChoicesView and GADMediaView.
-- | -- | --


https://developers.google.com/admob/ios/rel-notes

**Comment by yinjimmy** [comment]
need to upgrade the AdMob sdk.

**Comment by yinjimmy** [comment]
closed
