### ISSUE TITLE
Setup App to use Remote Config documentation

### ISSUE THREAD

**Issue by whitegfx** [sdkbox/issues#3]
## where ##
<http://docs.sdkbox.com/en/liveops/remote-config/>
## what ##
- Setup App to use Remote Config
```sdkbox::init( <application token>, <application secret> );``` change to actual method signature from header
- Refine desription for debug param (used for debug output?) ```void init( const char* application_token, const char* application_key, const char* store = "all", bool debug = false);```

Thank you

**Comment by darkdukey** [comment]
Documentation updated
