### ISSUE TITLE
Google Play Games Services, account creation, limited functionality on iOS

### ISSUE THREAD

**Issue by whitegfx** [sdkbox/issues#4]
## where ##
<http://docs.sdkbox.com/en/plugins/googleplay/v3-cpp/>
## what ##
- add warning for iOS, Account creation within iOS is no longer supported, refer to the blog post <https://android-developers.googleblog.com/2016/12/games-authentication-adopting-google.html>

**Comment by darkdukey** [comment]
Documentation updated
