### ISSUE TITLE
IAP finish transaction functionality on Android

### ISSUE THREAD

**Issue by haligalaph** [sdkbox/issues#41]
Same functionality as in #21 but on Android. I have no idea why it wasn't made, when implementing such a feature on iOS. For now iap plugin calls "consumePurchase" right after getting responce from Google Play, but it should do it in "finishTransaction" method called by user. Reason is the same as for iOS platform. If user has server side purchase validation, IAP could be lost, if server doesn't receive notification for some reason.

**Comment by hugohuang1111** [comment]
we implent `finishTransaction` on android, can you have a test？

https://www.dropbox.com/s/m77v5oxuakfloa7/sdkbox-iap_v2.3.17.6.tar.gz?dl=0
