### ISSUE TITLE
[AdMob] sdkbox::PluginAdMob::init() crash

### ISSUE THREAD

**Issue by angelvet** [sdkbox/issues#60]
I'm using SDKBox v2.4.3.3

On some Android devices on arm64-v8a platform AdMob plugin crashes on init.

Android version: 6.0, 7.0, 8.0

Devices:  
HUWEI MediaPad T3 (HWKobe-Q) 
M3 (hwbeethoven) 
HUAWEI MediaPad T3 10 (HWAGS-Q)
HUAWEI MediaPad T5 (HWAGS2)
HUAWEI MediaPad M5 lite (HWBAH2)
MediaPad T3 7 (hwbg2)

********** Crash dump: **********
pid: 0, tid: 0 >>> com.-.- <<<
Stack frame   #00  pc 000000000006bc40  /system/lib64/libc.so (tgkill+8)
Stack frame   #01  pc 00000000000690dc  /system/lib64/libc.so (pthread_kill+64)
Stack frame   #02  pc 0000000000023e68  /system/lib64/libc.so (raise+24)
Stack frame   #03  pc 000000000001c8ec  /system/lib64/libc.so (abort+52)
Stack frame   #04  pc 000000000042dda4  /system/lib64/libart.so (_ZN3art7Runtime5AbortEv+352)
Stack frame   #05  pc 00000000000e5324  /system/lib64/libart.so (_ZN3art10LogMessageD2Ev+1204)
Stack frame   #06  pc 00000000004508d0  /system/lib64/libart.so (_ZNK3art6Thread24AssertNoPendingExceptionEv+836)
Stack frame   #07  pc 00000000001246d8  /system/lib64/libart.so (_ZN3art11ClassLinker9FindClassEPNS_6ThreadEPKcNS_6HandleINS_6mirror11ClassLoaderEEE+68)
Stack frame   #08  pc 0000000000324970  /system/lib64/libart.so (_ZN3art3JNI9FindClassEP7_JNIEnvPKc+2780)
Stack frame   #09  pc 000000000157aeac  /data/app/com.-.--1/lib/arm64/lib-.so : Routine sdkbox::JNIUtils::**GetClassObjectFromName**(char const*, _JNIEnv*) at ??:?
Stack frame   #10  pc 000000000157b414  /data/app/com.-.--1/lib/arm64/lib-.so : Routine sdkbox::JNIUtils::**GetJNIStaticMethodInfo**(char const*, char const*, char const*, _JNIEnv*) at ??:?
Stack frame   #11  pc 00000000015779f0  /data/app/com.-.--1/lib/arm64/lib-.so : Routine std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > sdkbox::**JNIInvokeStatic**<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >>(char const*, char const*) at ??:?
Stack frame   #12  pc 0000000001577ba8  /data/app/com.-.--1/lib/arm64/lib-.so : Routine **_sdkbox::SdkboxCore::getNetworkType()_** const at ??:?
Stack frame   #13  pc 00000000015496e4  /data/app/com.-.--1/lib/arm64/lib-.so : Routine sdkbox::AdBooster::**adInit**() at ??:?
Stack frame   #14  pc 00000000015269f0  /data/app/com.-.--1/lib/arm64/lib-.so : Routine sdkbox::AdMobWrapperEnabled::**init**() at ??:?
Stack frame   #15  pc 0000000001526a38  /data/app/com.-.--1/lib/arm64/lib-.so : Routine **_sdkbox::PluginAdMob::init()_** at ??:?
Stack frame   #16  pc 000000000136d988  /data/app/com.-.--1/lib/arm64/lib-.so : Routine client::AdMobManager::initialize() at -:-
Stack frame   #17  pc 000000000137674c  /data/app/com.-.--1/lib/arm64/lib-.so : Routine AppDelegate::applicationDidFinishLaunching() at Classes/AppDelegate.cpp:82
Stack frame   #18  pc 000000000157d658  /data/app/com.-.--1/lib/arm64/lib-.so : Routine cocos2d::Application::run() at -/cocos2d/cocos/platform/android/CCApplication-android.cpp:71
Stack frame   #19  pc 0000000001583808  /data/app/com.-.--1/lib/arm64/lib-.so : Routine Java_org_cocos2dx_lib_Cocos2dxRenderer_nativeInit at -/cocos2d/cocos/platform/android/javaactivity-android.cpp:102
Stack frame   #20  pc 00000000008c0a1c  /data/app/com.-.--1/oat/arm64/base.odex

**Comment by yinjimmy** [comment]
hi @angelvet ,

Does the game still crash ?

**Comment by angelvet** [comment]
Hi @yinjimmy , I'm on v2.5.1.2 and it seems that this crash went away. Thanks.

**Comment by yinjimmy** [comment]
Let me close this issue.
Thanks,
