### ISSUE TITLE
Achievement notification are not displayed under iOS 9.3.5

### ISSUE THREAD

**Issue by whitegfx** [sdkbox/issues#7]
Achievement notification are not displayed under iOS 9.3.5.

## Enviroment ##
- iOS 9.3.5 (iPhone 4S) doesn't work (9.3.5 is the latest iOS for this device)
- 10.2 (iPhone 6) works
- on Android also works
- cocos2d-x 3.14.1, sdkboxplay 2.3.9, 2.3.10, OS Sierra 10.12.2, Xcode Version 8.2.1 (8C1002)

## Steps to reproduce ##
- check live ops achievement setup for notification checkbox (must be checked)
- check live ops sdkboxplay init on startup (must be checked)
- create incremental achievements, try to report steps to unlock them
- try to reset achievements, test again
- try another newly created iOS account, test again

**Comment by yinjimmy** [comment]
https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/GameKit_Guide/Achievements/Achievements.html#//apple_ref/doc/uid/TP40008304-CH7-SW8

```
When the progress reaches 100 percent, the achievement is marked as completed, and both the image and completed description appear when the player views the achievements screen.
```

**Comment by yinjimmy** [comment]
Fixed it.
