### ISSUE TITLE
Add achievement progress reset API method for iOS

### ISSUE THREAD

**Issue by whitegfx** [sdkbox/issues#8]
There is no way to easy reset achievement progress, unitl you know and add your own method.
Add method to sdkboxplay API to call achievement reset (this method may only work for debug config?).

thank you

**Comment by darkdukey** [comment]
`resetAchievements` has been implemented on 2.3.12, it's currently testing on staging

**Comment by whitegfx** [comment]
Ok, closing this is easy task, this will work on 100%.

**Comment by yinjimmy** [comment]
@whitegfx Thank you.
