### ISSUE TITLE
Ideas how to track more than 100 steps on iOS.

### ISSUE THREAD

**Issue by whitegfx** [sdkbox/issues#9]
sdkbox 2.3.11.3, mac osx, android/ios

**Intro ;)**
- Game often use achievements to track user progress. For ex. played games, killed zombies etc.
- from my understanding iOS have percentage completion up to 100% as double value, so increment must be sent as percentage value, increment is added to the actual steps.. Google have steps to complete, increment is added to the current value. Ok?
- Lets track killed zombies upt to 5000 kills.
- Sdkbox documentation, suggest to have 100 steps on the both platforms, 100 value is good for completed levels or other general things. Not for to track played games, zombie kills etc.

Maybe Im wrong, let me know please...

- on iOS make the incremental achievement
- increment 2 kills after game played. 2.0/5000.0 = 0.0004 * 100.0 = 0,04 as the increment
- problem, sdkbox increment method use int (due google requirement? increment must be int?), so there is no way to increment < 1% for iOS
- I have no problem to recalculate iOS percentage and google values to the actual progress, but fixed int is limiting to 100 steps/increments.
- on google there is possibility to set 5000 steps and increment with 1 as one kill, all is counted ok, problem is iOS

**Solutions**
- current steps and total steps already use numbers, thats great
- make methods (increment setsteps) to accept floats, pass floats to iOS as step or increment so they will be correctly counted. iOS accept float numbers as percentage.
- on google send fixed int
- user must recalculate steps for google and iOS, (percentage increment/step, and for google fixed int, increment/step)
- user must recalculate current and actual steps to get the progress
- we can use simple macro in the code to recalculate values

Let me know if you have any general idea/solution for both platforms how to track more than 100 kills in the easy way. (but avoid storing killed zombies locally etc.)

**Comment by darkdukey** [comment]
That's a good idea, we'll doing more research into this

**Comment by yinjimmy** [comment]
static void incrementAchievement( const std::string& achievement_name, int increment );

==>

static void incrementAchievement( const std::string& achievement_name, double increment );

**Comment by whitegfx** [comment]
@yinjimmy Hi, After update to v2.3.12.5 starting testing and found methods like onIncrementalAchievementStep, onIncrementalAchievementStepError, onSetSteps, onSetStepsError, setSteps that doesn't reflect increment double values.

**Comment by yinjimmy** [comment]
Got it.
